accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    
]

my_app/urls.py
from django.urls import path
from . import views

app_name = "my_app"
urlpatterns = [
    path("index/", views.index, name="index"),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include("my_app.urls")),
    path('accounts/', include("accounts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

my_app/models.py
from django.db import models

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    thumbnail = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # accounts.User를 직접 지정하지 않고, Django 함수 사용
        # 혹시 project의 user_model을 수정할 때 작업의 용이성을 위해
        model = get_user_model()
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        models = get_user_model()
        fields = ('username', 'email', )  # 원하는 field만 입력

my_app/forms.py
from django.db import models
from django import forms
from .models import Page

# Create your models here.
class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = "__all__"

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.views.decorators.http import require_http_methods, require_POST, require_safe

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('my_app:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('my_app:index')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('my_app:index')

def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # 회원가입 후 로그인처리
            auth_login(request, user)
            return redirect('my_app:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['POST'])
def delete(request):
    user = request.user
    user.delete()
    # 탈퇴 후 바로 로그아웃
    auth_logout(request)
    return redirect('accounts:index')

def update(request):
    if request.method == "POST":
        # update이기 때문에 instance 추가
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('my_app:index')
    else:
        # request를 보낸 user의 정보를 바로 넘김
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('my_app:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/change_password.html', context)

my_app/views.py
from django.shortcuts import render, redirect
from .models import Page
from .forms import PageForm

# Create your views here.
def index(request):
    page_list = Page.objects.all()
    context = {'page_list': page_list}
    return render(request, 'my_app/index.html', context)


def detail(request, pk):
    page = Page.objects.get(pk=pk)
    context = {'page': page}
    return render(request, 'my_app/detail.html', context)


def create(request):
    if request.method == 'POST':
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            page = form.save()
            return redirect('my_app:detail', page.pk)
    else:
        form = PageForm()

    context = {'form': form}
    return render(request, 'my_app/create.html', context)


def delete(request, pk):
    page = Page.objects.get(pk=pk)
    page.delete()
    return redirect('my_app:index')


def update(request, pk):
    page = Page.objects.get(pk=pk)

    if request.method == 'POST':
        form = PageForm(request.POST, request.FILES, instance=page)
        if form.is_valid():
            form.save()
            return redirect('my_app:detail', pk=page.pk)
    else:
        form = PageForm(instance=page)

    context = {'form': form, 'page': page}
    return render(request, 'my_app/update.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
  <h1>비밀번호변경</h1>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="변경하기">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
  <h1>회원정보수정</h1>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

my_app/templates/my_app/create.html
{% extends 'base.html' %} 

{% block content %}
  <h1>글작성</h1>
  <hr />

  <form
    action="{% url 'my_app:create' %}"
    method="POST"
    enctype="multipart/form-data">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="작성하기"/>
  </form>

  <br />
  <hr>
  <a href="{% url 'my_app:index' %}">목록보기</a>
{% endblock content %}

my_app/templates/my_app/detail.html
{% extends 'base.html' %} 

{% block content %}
  <h1>DETAIL</h1>
  <hr />

  {% if page.image %}
    <img src="{{page.image.url}}" />
  {% endif %}

  <div id="page-content">
    {% if page.thumbnail != "" %}
      <img width="120px" src="{{page.thumbnail.url}}" alt="">
    {% else %}
      <p>NO THUMBNAIL</p>
    {% endif %}
    <p>글 제목 : {{page.title}}</p>
    <p>글 내용 : {{page.content}}</p>
    <p>생성시각 : {{page.created_at}}</p>
    <p>수정시각 : {{page.updated_at}}</p>

    <hr>
    <a href="{% url 'my_app:update' page.pk %}">수정하기</a>
    <form action="{% url 'my_app:delete' page.pk %}" id="delete-form">
      {% csrf_token %}
      <input type="submit" value="삭제하기" id="delete-btn" />
    </form><br>
    <hr>
    <a href="{% url 'my_app:index' %}">목록보기</a>
  </div>
{% endblock content %}

my_app/templates/my_app/index.html
{% extends 'base.html' %} 

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'my_app:create' %}">작성하기</a>
  <hr />

  {% for page in page_list %}
    <p>
      {% if page.thumbnail != "" %}
        <img width="50px" src="{{page.thumbnail.url}}" alt="">
      {% endif %}
      [{{page.id}}] 
      <a href="{% url 'my_app:detail' page.pk %}" id="page-title">{{page.title}}</a>
    </p>
    <hr />
  {% endfor %} 

{% endblock content %}

my_app/templates/my_app/update.html
{% extends 'base.html' %} 

{% block content %}
  <h1>글수정</h1>
  <hr />

  <form action="{% url 'my_app:update' page.pk %}" method="POST"  enctype='multipart/form-data'>
    {% csrf_token %} {{form.as_p}}
    <input type="submit" />
  </form>

  <hr />
  <a href="{% url 'my_app:detail' page.pk %}">돌아가기</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Base</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>